overrides:
  '@hono/node-server': 2.1.1
  body-parser: 2.3.0
  'minimatch@>=9>brace-expansion': 5.0.9
  fast-uri: 4.1.4
  hono: 4.13.5
  ip-address: 10.7.0
  js-yaml: 5.4.1
  nanoid: 6.0.1
  undici: 8.10.1

minimumReleaseAgeExclude:
  - '@ai-sdk/gateway'
  - '@ai-sdk/google'
  - '@ai-sdk/openai'
  - '@ai-sdk/provider'
  - '@ai-sdk/provider-utils'
  - '@ai-sdk/xai'
  - '@types/node'
  - ai
  - electron-to-chromium
  - lucide-react
  - shadcn
  - fast-uri@4.1.4

allowBuilds:
  '@swc/core': true
  cbor-extract: true
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true
